name: delete_all_vms
label: Delete VMs on Node
description: This will delete all VMs on a compute node
type: template
extends:
variables:
  - name: minion
    description: Node
    default: compute-01.c.vistoq-demo.internal
    type_hint: text

snippets:
  - name: delete_vms
    file: delete_vms.j2


